language: ruby
rvm:
  - 2.2
  - jruby
  - rbx-2
os:
- linux
sudo: required
cache:
  bundler: true
  apt: true
  directories:
  - $HOME/.download
env:
  global:

before_install:
  - gem install jekyll

install:
  - jekyll -v
  - ls
  - pwd