language: ruby
rvm:
  - 2.2
os:
- linux
sudo: required
cache:
  bundler: true
  apt: true
  directories:
  - $HOME/.download
env:
  global:

before_install:
  - gem install jekyll

install:
  - jekyll build
 
script:
  - ls
  - cd _site
  - ls